### PR TITLE
Create company-jedi.el

### PR DESCRIPTION
**Pull request by boyw165**
Add company-backend for JEDI.

### CODE REVIEW

**Comment by IvanMalison** [comment]
++ what is the status of this pull request?

**Comment by PythonNut** [comment]
I just switched to `company`, and I'm very interested in jedi support. Does anything need doing? I might be able to help.

**Comment by boyw165** [comment]
Sorry, I'm too busy recently. It will be very nice if anyone can take care of the rest jobs of this patch.

**Comment by IvanMalison** [comment]
@boyw165 What needs to be done?

**Comment by gozes** [comment]
any chance that this PR will be merged soon?

**Comment by IvanMalison** [comment]
@boyw165 ping. I can finish this for you. It would be helpful to know what needs to be fixed/added.

**Comment by syohex** [comment]
Sorry too late reply. We should remove auto-complete dependency from `jedi.el`.

**Comment by IvanMalison** [comment]
But not auto-complete support right? So the idea would be to let users choose between company and auto-complete? Has anyone thought about making this a completion at point function (since company supports those)?

**Comment by syohex** [comment]
> But not auto-complete support right?

no.

Plan is

1. Remove auto-complete.el dependency from jedi.el
2. We create jedi-auto-complete.el for auto-complete user
3. Update package dependencies
4. Update MELPA recipe
5. Merge company-jedi patch
6. Send PR of company-jedi

**Comment by syohex** [comment]
@boyw165 Sorry very too late reply, I have merged this PR at #202.
And send company-jedi recipe to MELPA(https://github.com/milkypostman/melpa/pull/2554)

**Comment by syohex** [comment]
I'll move `company-jedi` to another repository, because it is difficult to manage both auto-complete
jedi and company-jedi in same repository

**Comment by asmeurer** [comment]
Is auto-complete still actively developed? If not, maybe it should be deprecated.

**Comment by syohex** [comment]
> Is auto-complete still actively developed?

auto-complete is still devloped, however it is not so actively.

**Comment by syohex** [comment]
You can install `company-jedi` from MELPA by
- `M-x package-install <RET> company-jedi <RET>`

Thanks for sending patch

**Comment by asmeurer** [comment]
Is that it? Does the configuration in .emacs need to change? Can you update the docs with this?

**Comment by syohex** [comment]
> Does the configuration in .emacs need to change?

Yes.

```lisp
(defun my/python-mode-hook ()
  (add-to-list 'company-backends 'company-jedi))

(add-hook 'python-mode-hook 'my/python-mode-hook)
```

And you need to use `company-complete` command instead of `jedi:complete`
or `jedi:dot-complete`. They depends on `auto-complete` much.


See
- https://github.com/syohex/emacs-company-jedi

> Can you update the docs with this?

I'll update later.

**Pull request closed without merging**
